groups:
  - name: casino_portal_alerts
    rules:
      # Website down alert
      - alert: WebsiteDown
        expr: up{job="website"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Best Casino Portal website is down"
          description: "The website has been down for more than 2 minutes"

      # API server alerts
      - alert: APIServerDown
        expr: up{job="casino-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Casino API server is down"
          description: "Main API server has been down for more than 1 minute"

      - alert: AnalyticsAPIDown
        expr: up{job="analytics-api"} == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Analytics API server is down"
          description: "Analytics API server has been down for more than 1 minute"

      # System resource alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 15
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 15%"

      # SSL Certificate expiry
      - alert: SSLCertificateExpiringSoon
        expr: (ssl_cert_expiry - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate will expire in less than 30 days"

      # Nginx alerts
      - alert: NginxDown
        expr: up{job="nginx"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Nginx is down"
          description: "Nginx web server has been down for more than 1 minute"

      - alert: HighErrorRate
        expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) / rate(nginx_http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for more than 5 minutes"
